# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  my-executor-for-build-run:
    docker:
      - image: circleci/node:7.10-browsers
          environment:
            MYSQL_HOST: 127.0.0.1
            MYSQL_DB: circleci
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_PASSWORD:
            MYSQL_DB_FILE: starlife.sql
      - image : circleci/mysql:5
          environment:
            command: mysqld --sql-mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/on-air-lab
jobs:
  build:
    executor: my-executor-for-build-run
    steps:
      - checkout
      # Download and cache dependencies
      - run: 
          name: "Install and run DB"
          command: |
            sudo apt-get update && sudo apt-get install -y mysql-server
            sudo mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -e "create database ${MYSQL_DB};use ${MYSQL_DB};source ${MYSQL_DB_FILE};SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
            dockerize -wait tcp://${MYSQL_HOST}:3306 -timeout 1m
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
  #run test
  run-test:
    executor: my-executor-for-build-run
    steps:
      - checkout
      - run: 
          name: "Install app"
          command: yarn install 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: 
          name: "Run test"
          command: |
           npm test
           curl localhost:4000/search
           npm stop
  #deployement
  #deploy:
  #  docker:
  #    - image: circleci/node:7.10-browsers 
  #  steps:
  #    - run:
  #        name: Deploy Over SSH
  #        command: |
  #          ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
workflows:
  version: 2
  build-run-deploy:
    jobs:
      - build:
          filters:
            tags: 
              only:
                - prod-tpm-centrale
                - /prod-tpm-.*/
      - run-test:
          filters:
            tags: 
              only:
                - prod-tpm-centrale
                - /prod-tpm-.*/
          requires:
          - build
    #  - deploy:
    #      requires:
    #        - build

