# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: circleci
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD:
      - image : circleci/mysql:8.0.4
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/on-air-lab

    steps:
      - checkout
      # Download and cache dependencies
      - run: sudo apt-get update && sudo apt-get install -y mysql-server
      #- run: service mysql start
      #- run: mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -e "create database ${MYSQL_DB};"
      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test
      #- run: xdg-open 172.20.0.3:4000/search
  #deployement
  #deploy:
  #  docker:
  #    - image: circleci/node:7.10-browsers 
  #  steps:
  #    - run:
  #        name: Deploy Over SSH
  #        command: |
  #          ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
    #  - deploy:
    #      requires:
    #        - build

